### ISSUE TITLE
Using redux-entity with multiple subapps/modules

### ISSUE THREAD

**Issue by kbzak** [lelandrichardson/redux-entity#3]
First of all: this project is a very interesting concept, thank you for sharing!

The example in the README is quite simple, but how would you approach more complex app, where there are multiple "subapps"/modules? Let's say we have a simple CRM application, with modules such as: users, tasks, projects etc, where each of these modules has multiple models/schemas (e.g for users: User, Group, Contact) and its own reducers. How should/may one approach structuring such application using `redux-entity`?

Thank you!

**Comment by lelandrichardson** [comment]
Hi @kbzak, thanks for asking. If the apps are truly separate, then you could just create different schemas, reducers, and stores for each of those apps, and it should work just fine.

Your example though seems like there could be one global schema to handle all of those things? CRMs are great apps with a lot of related data that's interconnected, and I think storing everything in one EntityStore would be a good thing, but I could be missing something.

**Comment by kbzak** [comment]
Thanks for the reply, @lelandrichardson!
The CRM was just an example, I'm working on a pretty complex app that has many "subapps", some of them "link" to models in another "subapp", but I'm certain that separation helps in this case.

Few more questions:
- can you elaborate on this point: "Asynchronous Validation + Form State"?
- I understand that "System for making user-land plugins" means that I can create custom Resources? Do you envision other kinds of integrations/plugins in `redux-entity`?

Thanks!

**Comment by lelandrichardson** [comment]
> "Asynchronous Validation + Form State"

I haven't completely figured this out yet, but I was thinking i'd have "Form State" like `Resource` classes that can more easily handle common complex form-based scenarios, such as mixed server and client validation, saving "drafts" etc.  I don't know exactly what this will look like yet or if I think it's necessary for a "v1", but it's something I'd like to explore.

> I understand that "System for making user-land plugins" means that I can create custom Resources?

Correct!

> Do you envision other kinds of integrations/plugins in redux-entity?

Maybe, but it's too early to tell. If you have any thoughts I'd love to hear them. Introducing graphql state traversal into the library has opened a couple of points where graphql custom resolution is probably needed, but I'm not sure I understand the right way to do it yet. It's possible there might be some sort of a wrapping around conventional action handling / data fetching, etc... but I'm not sure it belongs in this library or not.
